services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
    command: --storage-driver overlay2

  jenkins-server:
    build: ./jenkins/
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - proxy-network
      - jenkins

networks:
  jenkins:
    driver: bridge

  # Reference the pre-existing external network shared with Caddy
  proxy-network: # The name here can be different, but the 'name' property must match
    name: caddy-proxy-network # Use the exact name created earlier
    external: true

volumes:
  jenkins-docker-certs:
  jenkins-data:
